name: Docker Build and Deploy to GHCR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    strategy:
      matrix:
        include:
          - text_model: "BAAI/bge-small-en-v1.5"
            image_model: "Qdrant/clip-ViT-B-32-vision"
          - text_model: "intfloat/multilingual-e5-large"
            image_model: "Qdrant/Unicom-ViT-B-16"
          # Add more combinations as needed

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=${{ matrix.text_model }}-${{ matrix.image_model }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          TEXT_EMBEDDING_MODEL=${{ matrix.text_model }}
          IMAGE_EMBEDDING_MODEL=${{ matrix.image_model }}