name: Build and Deploy Text Embedding to GHCR (master)
on:
  push:
    branches: [ master ]
env:
  REGISTRY: ghcr.io
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  IMAGE_PREFIX: fastembed
jobs:
  build-and-push-image:
    strategy:
      matrix:
        include:
          - model_name: "BAAI/bge-small-en-v1.5"
            model_name_slash_free_lowercase: "baai-bge-small-en-v1.5"
          - model_name: "intfloat/multilingual-e5-large"
            model_name_slash_free_lowercase: "intfloat-multilingual-e5-large"
          # Add more combinations as needed
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get the commit hash
      id: get_hash
      run: echo ::set-output name=COMMIT_HASH::$(git rev-parse HEAD)
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      env:
        IMAGE_NAME: ${{ env.IMAGE_PREFIX }}-${{ matrix.model_name_slash_free_lowercase }}
      with:
        context: .
        file: ./docker/DockerfileTextEmbedding
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:${{ steps.get_hash.outputs.COMMIT_HASH }}
        build-args: |
          TEXT_EMBEDDING_MODEL=${{ matrix.model_name }}
